# Generated by Django 4.1.3 on 2023-01-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='disable_tag',
            field=models.BooleanField(default=False),
        ),
    ]
