# Generated by Django 4.1.3 on 2022-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='date_to_do',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='tasks_groups', to='tasks.group'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks_tags', to='tasks.tag'),
        ),
    ]
