# Generated by Django 4.1.3 on 2022-12-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_group_tag_alter_task_date_to_do_task_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_to_do']},
        ),
    ]
