# Generated by Django 4.1.3 on 2022-12-29 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_task_date_to_do_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='tags_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
