# Generated by Django 4.1.3 on 2022-12-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_groups_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_to_do',
            field=models.DateTimeField(blank=True),
        ),
    ]
