# Generated by Django 4.1.3 on 2022-12-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_tag_user_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
