# Generated by Django 4.1.3 on 2022-12-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank='default.jpg', default='default.jpg', null='default.jpg', upload_to='profile_pics'),
        ),
    ]
