# Generated by Django 4.1.3 on 2023-01-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_option_disable_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='disable_tag',
        ),
    ]
